nginx1.7.4: using "-Werror"
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/src/ngx_http_mongo_module.o \
		./ngx_mongo//src/ngx_http_mongo_module.c
./ngx_mongo//src/ngx_http_mongo_module.c: In function ‘ngx_http_mongo_create_predefined_request’:
./ngx_mongo//src/ngx_http_mongo_module.c:681:28: error: variable ‘mctx’ set but not used [-Werror=unused-but-set-variable]
     ngx_http_mongo_ctx_t  *mctx;
                            ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_mongo_module.o] Error 1
make[1]: Leaving directory `/usr/src/nginx-1.7.4'
make: *** [build] Error 2